### ISSUE TITLE
[Feature Request]: Get World News in fotmob

### ISSUE THREAD

**Issue by ghost** [bgrnwd/fotmob#377]
### What feature would you like to see?

Hi @bgrnwd. First of all. I want to said that i really enjoy your wrapper. Im using you for my personal app about Football. The thing is i feel is missing the News from the world section in Fotmob
The url: https://www.fotmob.com/world.
So i hope you can actually adds in the future.. 
Thanks you so much

**Comment by bgrnwd** [comment]
Hi @buinguyenhoangtho, I took at look at the URL you mentioned and unfortunately it doesn't look like there's an API endpoint for world news. Since there isn't an endpoint available, adding this to `fotmob` would be a larger effort and involve HTML parsing. I don't think it's something I'd add at the moment but if someone wants to give it a go, I'm happy to review pull requests.
